# Generated by Django 4.1 on 2022-08-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_date',
            field=models.DateTimeField(blank=True),
            preserve_default=False,
        ),
    ]
